### ISSUE TITLE
Add CFP Data?

### ISSUE THREAD

**Issue by martinwoodward** [finspin/gotodevops.org#21]
Hey - great list!  How would you feel about adding an entry into the conferences.yml to collect Call For Papers (CFP) deadline information?  I can have a go at sending a PR though if it's something that you are interested in tracking?

**Comment by finspin** [comment]
Sure, it would be a great addition! Feel free to submit a PR. I guess the structure could be something like this:

```
- name: NDC London
  url: https://ndc-london.com/
  location:
      city: London
      country: UK
  date: January 15 - 19, 2018
  start-date: 1515974400
  cost: 2
  call-for-papers:
      deadline: 1515974400
```
